### ISSUE TITLE
3.0.0 新版本计划

### ISSUE THREAD

**Issue by youngjuning** [youngjuning/wx-promise-pro#27]
- [x] 新项目名 wx-promise-pro
- [x] 清理冗余代码 https://github.com/youngjuning/wx-promise-pro/commit/a5cc84ec6036b6d0bf3446a1503bce51ab46d4b5
- [x] 支持typescript
- [ ] 添加自定义方法

**Comment by youngjuning** [comment]
@zwmmm 是的，现在小程序已经支持npm，会以按需加载的方式提供这些扩展方法！

**Comment by zhi-he** [comment]
3.0什么时候出

**Comment by youngjuning** [comment]
不好意思哦，这半年主要写 React Native 了，近期我在看下小程序目前最新的生态。进行3.0的适配开发工作、大家有什么好的建议可以在这里提出来

**Comment by abrahamgreyson** [comment]
能否把冗余代码清理下， 现在维护一个私有分支，太麻烦

**Comment by youngjuning** [comment]
@abrahamgreyson 已经移除，wxPromise.min.js 中只留了核心功能，regenerator-runtime 单独放到了一个文件，自定义的扩展功能我会在搞一个文件，又需要的引入，没有需要不引
