### ISSUE TITLE
wx.canvasToTempFilePath有问题

### ISSUE THREAD

**Issue by zhi-he** [youngjuning/wx-promise-pro#31]
![image](https://user-images.githubusercontent.com/31757470/59413723-ae74c100-8df2-11e9-940f-70b16366df97.png)
![image](https://user-images.githubusercontent.com/31757470/59413769-c9dfcc00-8df2-11e9-944d-2d8a3a59b4bd.png)
这有问题吧，wx.canvasToTempFilePath方法本身不需要canvasContext对象，这样的话，我连保存的的类型为JPG都不行了，下个版本什么时候出。期待...

**Comment by youngjuning** [comment]
这个方法还有需求对吧，我本来打算移除了。哈哈

**Comment by zhi-he** [comment]
别啊，还在用呢：)
