### ISSUE TITLE
app.json使用了插件时，每次执行promise报以下错误，不影响执行结果

### ISSUE THREAD

**Issue by zx86119** [youngjuning/wx-promise-pro#33]
[non-writable] modification of global variable "Promise.prototype.finally" is not allowed when using plugins at app.json.

**Comment by zx86119** [comment]
和微信版本有关，真机基本无此报错，不影响使用

**Comment by youngjuning** [comment]
https://github.com/youngjuning/wx-promise-pro/commit/7f0b4ba1f6afa6a658940ebeff432801c67e34c0 fix it
