### ISSUE TITLE
为什么报这个错误

### ISSUE THREAD

**Issue by neozhu** [youngjuning/wx-promise-pro#37]
thirdScriptError
Unexpected token {
SyntaxError: Unexpected token {
````
import { promisifyAll, promisify } from 'wx-promise-pro';
promisifyAll()
//index.js
//获取应用实例
const app = getApp()

Page({

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/76045229-6789b580-5f97-11ea-8bc1-9f9ea9bd99f2.png)

可能是编译选项需要开启，你是直接引用还是NPM引入

**Comment by youngjuning** [comment]
你可能需要给我个复现环境了

**Comment by neozhu** [comment]
我找到问题了就是没有勾选 ES6 to ES5
但这里又有一个问题，我想原生支持 async/await  onLoad: async function(){ } 然后 就可以直接 用 await 了，不然在 一个普通的方法中调用 async 方法总觉得哪里不对。
这个问题我也腾讯官方问过，说白就是对ES7 ES8的支持不够。不知道腾讯怎么想的，是偷懒还是真的为了向下兼容

**Comment by youngjuning** [comment]
没太看明白你的问题，如果只是想支持 async await，你开启增强编译即可

**Comment by youngjuning** [comment]
我先关了issues，有问题，技术问题可以加我微信，文档底部有

**Comment by neozhu** [comment]
哦，明白了，可以了，谢谢回复，问题解决了

**Comment by youngjuning** [comment]
3.2.0 源码配置了 babel ES6 to ES5，可以不开启ES6编译了，但是建议还是使用ES6开发
