### ISSUE TITLE
引入后报错 module "wx-promise-pro" is not defined

### ISSUE THREAD

**Issue by SHERlocked93** [youngjuning/wx-promise-pro#38]
引入的时候就报错，代码如下
```js
import { promisifyAll } from 'wx-promise-pro'
```

![image](https://user-images.githubusercontent.com/24636076/80954298-b6d15280-8e2f-11ea-8d9e-2780d9c39536.png)

配置见下图

![image](https://user-images.githubusercontent.com/24636076/80954337-c6e93200-8e2f-11ea-960f-4194b4005082.png)

**Comment by SHERlocked93** [comment]
找到问题了，在 `npm install` 的时候，必须要加上 `-S` 或者 `--production` 才可以构建成功

**Comment by youngjuning** [comment]
我使用的是 Yarn，更方便一点

**Comment by youngjuning** [comment]
我说呢，这个头像这么熟悉，原来是掘金大佬

**Comment by SHERlocked93** [comment]
> 我说呢，这个头像这么熟悉，原来是掘金大佬

🤣 才开始搞小程序，见笑了，向大家学习
