### ISSUE TITLE
Error: APP-SERVICE-SDK:createSignal:fail rejected due to no permission currently

### ISSUE THREAD

**Issue by trampboy** [youngjuning/wx-promise-pro#43]
今天发布后出现错误日志如下：
```
APP-SERVICE-SDK:createSignal:fail rejected due to no permission currently
Error: APP-SERVICE-SDK:createSignal:fail rejected due to no permission currently
at Object.createSignal (https://lib/WASubContext.js:2:1826102)
at https://miniprogram_npm/wx-promise-pro/index.js:8:3923
at c (https://miniprogram_npm/wx-promise-pro/index.js:8:3857)
at ve.onLaunch (https://app.js:148:7)
at ve.<anonymous> (https://lib/WASubContext.js:2:2124238)
at new ve (https://lib/WASubContext.js:2:2124994)
at Function.<anonymous> (https://lib/WASubContext.js:2:2125306)
at https://lib/WASubContext.js:2:2111785
at https://app.js:48:1
```
使用Source Map 定位发现错误代码位置是：
```javascript
n=function(){wx.pro={},Object.keys(wx).forEach((function(e){a.indexOf(e)>=0?wx.pro[e]=r(wx[e]):wx.pro[e]=wx[e]}))}
```
感觉是赋值 wx.pro[createSignal]=wx[createSignal] 出现的问题

**Comment by youngjuning** [comment]
你排查的方向可能错了： https://developers.weixin.qq.com/community/develop/doc/00020636798248eaeb9aa476051400

**Comment by trampboy** [comment]
@youngjuning 
你好，非常感谢你的回复。
我知道这个问题是违规调用未开放的微信基础库 createSignal 接口导致的，但目前只有在 wx-promise-pro 内部才被使用。我现在移除 wx-promise-pro 后错误日志消失。

**Comment by youngjuning** [comment]
@trampboy 没有执行也能报，这官方。。。我暂时过滤掉吧

**Comment by youngjuning** [comment]
> @youngjuning
> 你好，非常感谢你的回复。
> 我知道这个问题是违规调用未开放的微信基础库 createSignal 接口导致的，但目前只有在 wx-promise-pro 内部才被使用。我现在移除 wx-promise-pro 后错误日志消失。
是只有发布到正式环境才会有吗？

**Comment by youngjuning** [comment]
fix on https://github.com/youngjuning/wx-promise-pro/commit/d50c3b0d945834b0cfed0914e9a1a48d91b6ca7e，wx-promise-pro@3.2.2 已发布！

**Comment by trampboy** [comment]
@youngjuning 
太高效了，非常感谢！
其实我也觉得很奇怪，赋值为什么会触发，目前我能想到的是会不会因为 Proxy。
如果是这样，是不是做一层异常捕获会比较好。
之后有空我验证下。

**Comment by trampboy** [comment]
> > @youngjuning
> > 你好，非常感谢你的回复。
> > 我知道这个问题是违规调用未开放的微信基础库 createSignal 接口导致的，但目前只有在 wx-promise-pro 内部才被使用。我现在移除 wx-promise-pro 后错误日志消失。
> 
> 是只有发布到正式环境才会有吗？

我是在微信小程序开发后台-错误日志看到的，不是所有的人都会遇到，可能是灰度的基础库导致的，找不到具体的基础库版本信息。

**Comment by youngjuning** [comment]
感谢建议，捕获一下异常确实是一劳永逸，感谢！

**Comment by youngjuning** [comment]
#45
