### ISSUE TITLE
Error: APP-SERVICE-SDK:lanDebug:fail rejected due to no permission currently报错

### ISSUE THREAD

**Issue by hzy1216** [youngjuning/wx-promise-pro#45]
Error: APP-SERVICE-SDK:lanDebug:fail rejected due to no permission currently报错问题，在src/index.js中加入key !== "createSignal" && key !== "lanDebug"

**Comment by youngjuning** [comment]
@hzy1216 大佬可以提一个 PR 支持一下😊

**Comment by youngjuning** [comment]
like this #43

**Comment by youngjuning** [comment]
fix on https://github.com/youngjuning/wx-promise-pro/commit/dab90c7a1881c71da4f412e61667e6204b043965，publish on 3.2.4
